### ISSUE TITLE
Spoof TLS/JA3 fingerprints

### ISSUE THREAD

**Issue by spoNge369** [RedTeamPentesting/monsoon#12]
Hi guys :D, is there a possibility to implement in the http client can supplant the TLS fingerprint, something like this: [https://github.com/Danny-Dasilva/CycleTLS](url).

Regards :smiley:

**Comment by rtpt-erikgeiser** [comment]
Sorry for the late replay. At the moment there are no plans to support custom TLS fingerprints.

I'd recommend writing a small SOCKS-Proxy with a custom TLS client and using monsoon through that proxy.
