### ISSUE TITLE
The show-status / hide-status flags don't work with multiple status codes

### ISSUE THREAD

**Issue by mrschyte** [RedTeamPentesting/monsoon#5]
Monsoon doesn't show matched responses if multiple status codes are specified.

For example a similar command to the one below shows that multiple responses have been seen with status code 302 (in the status code display on the bottom), however no results are shown in the results table.
`$ monsoon fuzz https://example.com/FUZZ -f wordlist.txt --show-status 301,302`

If I specify only a single status code or a range as follows, then the results table is populated.
`$ monsoon fuzz https://example.com/FUZZ -f wordlist.txt --show-status 302`
`$ monsoon fuzz https://example.com/FUZZ -f wordlist.txt --show-status 301-302`

**Comment by rtpt-alexanderneumann** [comment]
Oh, you're right, thanks for the hint! There's probably a logic error in the filtering logic.

**Comment by mrschyte** [comment]
Thanks, the fix works like a charm :+1:
