### ISSUE TITLE
No bug - filter the file size

### ISSUE THREAD

**Issue by Teicu** [RedTeamPentesting/monsoon#9]
Hello, 

In order to enhance the fuzzer's effectiveness, it is crucial to incorporate a file size filtering option. Neglecting this feature can render the fuzzer's response futile at times, as illustrated in the attached image. 

Cheers

<img width="945" alt="Screenshot 2023-07-12 at 16 58 03" src="https://github.com/RedTeamPentesting/monsoon/assets/1572822/0a026169-9689-441b-8dd5-20a0a2d4b609">

**Comment by rtpt-erikgeiser** [comment]
Hi,

Thanks for your feedback. There are already a lot of filtering options, but I think you are looking for `--hide-body-size 171064`. It can be specified multiple times and it supports ranges of file sizes.

Currently, the following filters are available:
```
--hide-status code,[code-code],[-code],[...]   hide responses with this status code,[code-code],[-code],[...]
--show-status code,[code-code],[code-],[...]   show only responses with this status code,[code-code],[code-],[...]
--hide-header-size size,from-to,from-,-to      hide responses with this header size (size,from-to,from-,-to)
--hide-body-size size,from-to,from-,-to        hide responses with this body size (size,from-to,from-,-to)
--hide-pattern regex                           hide responses containing regex in response header or body (can be
                                                specified multiple times)
--show-pattern regex                           show only responses containing regex in response header or body (can be
                                                specified multiple times)
```

I hope that helps :slightly_smiling_face:
